services:
  minecraft-motd-server:
    build: .
    restart: always
    environment:
      - PORT=25565
      - MOTD
      - VERSION_NAME
      - KICK_MESSAGE
      - HOST
    ports:
      - ${PORT}:25565
